# Generated by Django 5.1.3 on 2025-02-25 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameter",
            name="t_id",
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="s_id",
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
        migrations.DeleteModel(
            name="Parameter",
        ),
        migrations.DeleteModel(
            name="Tool",
        ),
        migrations.DeleteModel(
            name="Prompt",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
