# Generated by Django 5.1.3 on 2025-02-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="s_starred",
            field=models.BooleanField(default=False),
        ),
    ]
