# Generated by Django 5.1.3 on 2025-02-25 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0002_section_s_starred"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="s_price",
        ),
        migrations.RemoveField(
            model_name="section",
            name="s_total_tokens",
        ),
        migrations.AddField(
            model_name="prompt",
            name="pr_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prompt",
            name="pr_price",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prompt",
            name="pr_token",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
