# Generated by Django 5.1.3 on 2025-02-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "database_service",
            "0003_remove_section_s_price_remove_section_s_total_tokens_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="s_name",
            field=models.CharField(max_length=50),
        ),
    ]
