# Generated by Django 5.1.3 on 2025-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0004_alter_section_s_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("c_color_id", models.CharField(max_length=10)),
                ("c_title", models.CharField(default="Untitled", max_length=50)),
                (
                    "c_description",
                    models.TextField(default="No description available."),
                ),
                ("c_background", models.CharField(max_length=50)),
                ("c_foreground", models.CharField(max_length=50)),
            ],
        ),
    ]
