# Generated by Django 5.1.3 on 2025-03-01 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0005_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(default="Untitled", max_length=50)),
                ("c_starred", models.BooleanField(default=False)),
                (
                    "c_created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="s_id",
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("m_id", models.AutoField(primary_key=True, serialize=False)),
                ("m_role", models.CharField(max_length=50)),
                ("m_content", models.TextField()),
                ("m_raw", models.TextField()),
                ("m_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_service.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolCall",
            fields=[
                ("tc_id", models.AutoField(primary_key=True, serialize=False)),
                ("tc_name", models.CharField(max_length=50)),
                ("tc_arguments", models.JSONField(default=dict)),
                ("tc_result", models.JSONField(default=dict)),
                (
                    "m_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_service.message",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Parameter",
        ),
        migrations.DeleteModel(
            name="Tool",
        ),
        migrations.DeleteModel(
            name="Prompt",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
