# Generated by Django 5.1.3 on 2025-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "database_service",
            "0006_conversation_remove_prompt_s_id_message_toolcall_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="c_messages",
            field=models.JSONField(default=dict),
        ),
    ]
