# Generated by Django 5.1.3 on 2025-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0007_conversation_c_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="c_messages",
            field=models.JSONField(default=list),
        ),
    ]
