# Generated by Django 5.1.3 on 2025-03-05 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0008_alter_conversation_c_messages"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="c_starred",
            new_name="c_deleted",
        ),
    ]
