# Generated by Django 5.1.3 on 2025-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0009_rename_c_starred_conversation_c_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="c_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="c_examples",
            field=models.JSONField(default=list),
        ),
    ]
