# Generated by Django 5.1.3 on 2025-03-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0010_category_c_active_category_c_examples"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="c_description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="category",
            name="c_title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
