# Generated by Django 5.1.3 on 2025-03-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "database_service",
            "0011_alter_category_c_description_alter_category_c_title",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="c_active",
            new_name="cat_active",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="c_background",
            new_name="cat_background",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="c_color_id",
            new_name="cat_color_id",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="c_description",
            new_name="cat_description",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="c_examples",
            new_name="cat_examples",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="c_foreground",
            new_name="cat_foreground",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="c_id",
            new_name="cat_id",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="c_title",
            new_name="cat_title",
        ),
        migrations.AddField(
            model_name="category",
            name="cat_event_prefix",
            field=models.CharField(default="", max_length=12),
        ),
    ]
