# Generated by Django 5.1.3 on 2025-03-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0012_rename_c_active_category_cat_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_event_prefix",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="category",
            name="cat_title",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
