# Generated by Django 5.1.3 on 2025-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0013_alter_category_cat_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyValueStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("value_type", models.CharField(default="str", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["key"], name="database_se_key_2393d7_idx")
                ],
            },
        ),
    ]
