# Generated by Django 5.1.3 on 2025-03-24 04:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0014_keyvaluestore"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "u_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("u_email", models.EmailField(max_length=254, unique=True)),
                ("u_google_auth", models.JSONField(default=dict)),
            ],
        ),
    ]
