# Generated by Django 5.1.3 on 2025-03-24 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0015_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolcall",
            name="m_id",
        ),
        migrations.AddField(
            model_name="category",
            name="u_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="database_service.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conversation",
            name="u_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="database_service.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userinfo",
            name="u_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="database_service.user",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="ToolCall",
        ),
    ]
