# Generated by Django 5.1.3 on 2025-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0017_alter_conversation_c_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="c_rawmessages",
            field=models.TextField(default=""),
        ),
        migrations.RunSQL(
            """
            CREATE INDEX c_rawmessages_search_idx 
            ON database_service_conversation 
            USING GIN (to_tsvector('english', c_rawmessages));
            """
        ),
    ]
