# Generated by Django 5.1.3 on 2025-04-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database_service", "0017_alter_conversation_c_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="c_rawmessages",
            field=models.TextField(default=""),
        ),
        migrations.RunSQL(
            """
            CREATE EXTENSION IF NOT EXISTS pg_trgm;
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX c_rawmessages_trgm_idx 
            ON your_app_conversation 
            USING GIN (c_rawmessages gin_trgm_ops);
            """
        ),
    ]
